# Include every speaker ID and amplifier alias before the encrypted root is available.
FILES+=(
  /usr/lib/firmware/updates/cirrus/cs35l56-b2-dsp1-misc-10280e54-spkid1-ampl.bin.zst
  /usr/lib/firmware/updates/cirrus/cs35l56-b2-dsp1-misc-10280e54-spkid1-ampr.bin.zst
  /usr/lib/firmware/updates/cirrus/cs35l56-b2-dsp1-misc-10280e54-spkid1.wmfw.zst
  /usr/lib/firmware/updates/cirrus/cs35l56-b2-dsp1-misc-10280e54-spkid2-ampl.bin.zst
  /usr/lib/firmware/updates/cirrus/cs35l56-b2-dsp1-misc-10280e54-spkid2-ampr.bin.zst
  /usr/lib/firmware/updates/cirrus/cs35l56-b2-dsp1-misc-10280e54-spkid2.wmfw.zst
  /usr/lib/firmware/updates/cirrus/cs35l56-b2-dsp1-misc-10280e54-spkid3-ampl.bin.zst
  /usr/lib/firmware/updates/cirrus/cs35l56-b2-dsp1-misc-10280e54-spkid3-ampr.bin.zst
  /usr/lib/firmware/updates/cirrus/cs35l56-b2-dsp1-misc-10280e54-spkid3.wmfw.zst
)
