//! Validator for OPR packaging requests.
//!
//! A request file is the only artifact in this system authored outside the
//! project. Everything downstream is generated by the factory and reviewed by
//! a maintainer, so this validator is the first and cheapest place a bad
//! request stops. It runs on every PR with no network, no secrets and no code
//! execution.
//!
//! The rules are numbered as they are in `docs/request-schema.md`.

pub mod catalogue;
pub mod diagnostic;
pub mod license;
pub mod loader;
pub mod net;
pub mod redact;
pub mod rules;
pub mod schema;

pub mod cli;

use catalogue::Catalogue;
use diagnostic::Violation;
use license::Allowlist;
use net::Http;
use rules::{OfflineCx, Request};
use schema::Schema;
use std::path::Path;

/// The outcome of validating one file.
pub struct Report {
    pub path: String,
    pub violations: Vec<Violation>,
}

impl Report {
    pub fn is_valid(&self) -> bool {
        self.violations.is_empty()
    }
}

/// Everything the validator needs, assembled once and reused across files.
pub struct Validator {
    schema: Schema,
    cx: OfflineCx,
}

impl Validator {
    pub fn new(schema: Schema, catalogue: Option<Catalogue>, allowlist: Allowlist) -> Self {
        Self {
            schema,
            cx: OfflineCx {
                catalogue,
                allowlist,
            },
        }
    }

    /// Rules 1-5 and 7-11. Opens no socket.
    ///
    /// Note the absence of an `Http` parameter: there is no handle here for a
    /// rule to reach the network with, so the offline guarantee is a property
    /// of the signature rather than of anyone's discipline.
    pub fn check_offline(&self, path: &Path) -> Report {
        let display = path.display().to_string();

        let value = match loader::load(path) {
            Ok(v) => v,
            // A file that will not parse cannot be checked further. Reporting
            // one real problem beats reporting eleven consequences of it.
            Err(loader::LoadError::Invalid(v)) => {
                return Report {
                    path: display,
                    violations: vec![v],
                }
            }
            Err(loader::LoadError::Unreadable(m)) => {
                return Report {
                    path: display,
                    violations: vec![Violation::new(
                        diagnostic::Rule::Structure,
                        "<file>",
                        redact::show(&m),
                        "check the path and permissions",
                    )],
                }
            }
        };

        Report {
            path: display,
            violations: self.check_value_offline(&value),
        }
    }

    /// Split out so tests can drive the rule set without touching the disk.
    pub fn check_value_offline(&self, value: &serde_json::Value) -> Vec<Violation> {
        let mut violations = self.schema.check(value);

        // Native rules run even when the schema found problems, so one pass
        // reports everything wrong with the file. Each rule declines when its
        // own input is missing; see `rules::Request`.
        let request = Request::new(value);
        for rule in rules::offline_rules() {
            violations.extend(rule.check(&request, &self.cx));
        }

        diagnostic::sort(&mut violations);
        violations
    }

    /// Rule 6 only. Callers run this in addition to `check_offline`.
    pub fn check_resolve(&self, value: &serde_json::Value, net: &dyn Http) -> Vec<Violation> {
        let request = Request::new(value);
        let mut violations = Vec::new();
        for rule in rules::resolve_rules() {
            violations.extend(rule.check(&request, net));
        }
        diagnostic::sort(&mut violations);
        violations
    }

    /// Both stages against one file.
    pub fn check_all(&self, path: &Path, net: &dyn Http) -> Report {
        let mut report = self.check_offline(path);

        // Only meaningful if the file parsed; a document that failed to load
        // has nothing to resolve.
        if let Ok(value) = loader::load(path) {
            report.violations.extend(self.check_resolve(&value, net));
            diagnostic::sort(&mut report.violations);
        }

        report
    }
}
