PACKAGE_NAME="vision-drivers"
PACKAGE_VERSION="@PKGVER@"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="intel_cvs"
BUILT_MODULE_LOCATION[0]=""
DEST_MODULE_LOCATION[0]="/updates"

MAKE[0]="make KERNEL_SRC=${kernel_source_dir}"
CLEAN="make KERNEL_SRC=${kernel_source_dir} clean"
