PACKAGE_NAME="ipu7-drivers"
PACKAGE_VERSION="@PKGVER@"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="intel-ipu7"
BUILT_MODULE_LOCATION[0]="drivers/media/pci/intel/ipu7/"
DEST_MODULE_LOCATION[0]="/updates"

BUILT_MODULE_NAME[1]="intel-ipu7-isys"
BUILT_MODULE_LOCATION[1]="drivers/media/pci/intel/ipu7/"
DEST_MODULE_LOCATION[1]="/updates"

BUILT_MODULE_NAME[2]="intel-ipu7-psys"
BUILT_MODULE_LOCATION[2]="drivers/media/pci/intel/ipu7/psys/"
DEST_MODULE_LOCATION[2]="/updates"

BUILT_MODULE_NAME[3]="ipu-acpi"
BUILT_MODULE_LOCATION[3]="drivers/media/platform/intel/"
DEST_MODULE_LOCATION[3]="/updates"

BUILT_MODULE_NAME[4]="ipu-acpi-pdata"
BUILT_MODULE_LOCATION[4]="drivers/media/platform/intel/"
DEST_MODULE_LOCATION[4]="/updates"

BUILT_MODULE_NAME[5]="ipu-acpi-common"
BUILT_MODULE_LOCATION[5]="drivers/media/platform/intel/"
DEST_MODULE_LOCATION[5]="/updates"

MAKE[0]="make BUILD_INTEL_IPU_ACPI=1 KERNEL_SRC=${kernel_source_dir}"
CLEAN="make KERNEL_SRC=${kernel_source_dir} clean"
