PACKAGE_NAME="snd_hda_macbookpro"
PACKAGE_VERSION="@PKGVER@"
PRE_BUILD="./prepare-dkms-build $kernelver"
MAKE[0]="make KERNELBUILD=$kernel_source_dir"
BUILT_MODULE_NAME[0]="snd-hda-codec-cs8409"
BUILT_MODULE_LOCATION[0]="build/hda/codecs/cirrus"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
