#!/usr/bin/python3
"""Remove NVIDIA 610's deprecation annotations from legacy scalar version fields."""
import os
import re
import subprocess
import sys


def normalize(text):
    return re.sub(r'(?m)^((?:Driver|CUDA) Version[ \t]*:[ \t]*[0-9.]+)[ \t]+\[Deprecated;[^\n]*\]$', r'\1', text)


def main(args):
    real = '/usr/bin/nvidia-smi'
    if args == ['-q', '--display=COMPUTE']:
        result = subprocess.run([real, *args], stdout=subprocess.PIPE, text=True)
        sys.stdout.write(normalize(result.stdout))
        return result.returncode
    os.execv(real, [real, *args])


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
