#!/usr/bin/python3
"""Manage the native local service on Arch; delegate other CLI operations."""
import getpass
import json
import os
from pathlib import Path
import subprocess
import sys
import time
import urllib.request

VENDOR = '/opt/NVIDIA AI Workbench/resources/bin/nvwb-cli-full'
UNIT = 'nvwb-spark@' + getpass.getuser() + '.service'


def ready():
    try:
        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
        with opener.open('http://127.0.0.1:10001/v1/version', timeout=2) as response:
            info = json.load(response)
        return info.get('username') == getpass.getuser() and bool(info.get('version'))
    except (OSError, ValueError):
        return False


def main(args):
    default_dir = Path.home() / '.nvwb'
    workbench_dir = default_dir
    for i, arg in enumerate(args):
        if arg == '--workbench-dir' and i + 1 < len(args):
            workbench_dir = Path(args[i + 1]).expanduser()
        elif arg.startswith('--workbench-dir='):
            workbench_dir = Path(arg.split('=', 1)[1]).expanduser()
    if workbench_dir == default_dir and args[-3:] == ['internal', 'ensure-context-ready', 'local']:
        if ready():
            return 0
        result = subprocess.run(['/usr/bin/sudo', '-n', '/usr/bin/systemctl', 'start', UNIT])
        if result.returncode:
            return result.returncode
        for _ in range(20):
            if ready():
                return 0
            time.sleep(1)
        print('Native Workbench service did not become ready; inspect journalctl -u '+UNIT, file=sys.stderr)
        return 1
    if workbench_dir == default_dir and args[-3:] == ['internal', 'shutdown-context', 'local']:
        return subprocess.run(['/usr/bin/sudo', '-n', '/usr/bin/systemctl', 'stop', UNIT]).returncode
    os.execv(VENDOR, [VENDOR, *args])


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
