PACKAGE_NAME="gb10-cx7-hotplug"
PACKAGE_VERSION="@VERSION@"
BUILT_MODULE_NAME[0]="gb10-cx7-hotplug"
DEST_MODULE_LOCATION[0]="/kernel/drivers/platform/arm64"
MAKE[0]="make KDIR=/usr/lib/modules/${kernelver}/build"
AUTOINSTALL="no"
