PACKAGE_NAME="latitude7320-camera"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="intel_skl_int3472_tps68470"
BUILT_MODULE_NAME[1]="ov5675"
BUILT_MODULE_NAME[2]="ipu-bridge"
BUILT_MODULE_NAME[3]="ov8856"
BUILT_MODULE_NAME[4]="dw9714"
DEST_MODULE_LOCATION[0]="/updates/dkms"
DEST_MODULE_LOCATION[1]="/updates/dkms"
DEST_MODULE_LOCATION[2]="/updates/dkms"
DEST_MODULE_LOCATION[3]="/updates/dkms"
DEST_MODULE_LOCATION[4]="/updates/dkms"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
AUTOINSTALL="yes"
