monitor.v4l2.rules = [
  {
    matches = [ { node.description = "~Latitude Front Camera.*" } ]
    actions = { update-props = {
      node.description = "Latitude Front Camera"
      node.nick = "Latitude Front Camera"
      node.pause-on-idle = true
    } }
  }
  {
    matches = [ { node.description = "~Latitude Rear Camera.*" } ]
    actions = { update-props = {
      node.description = "Latitude Rear Camera"
      node.nick = "Latitude Rear Camera"
      node.pause-on-idle = true
    } }
  }
]
